<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Autofac.Extensions.DependencyInjection" Version="11.0.0" />
    <PackageReference Include="Dapper" Version="2.1.72" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Legacy.Framework.FileManager\Legacy.Framework.FileManager.csproj" />
    <ProjectReference Include="..\..\Shared\Legacy.Shared\Legacy.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Status\" />
  </ItemGroup>

</Project>
